services:
  - type: web
    name: visual-search
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install scikit-learn==1.0.2
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: WOOCOMMERCE_BASE_URL
        sync: false
      - key: WOOCOMMERCE_CONSUMER_KEY
        sync: false
      - key: WOOCOMMERCE_CONSUMER_SECRET
        sync: false
      - key: RENDER
        value: true