name: Deploy Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Create Directories
      run: |
        mkdir -p product_images
        mkdir -p uploads
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
        
    - name: Create env file
      run: |
        echo "WOOCOMMERCE_URL=${{ secrets.WOOCOMMERCE_URL }}" > .env
        echo "WOOCOMMERCE_CONSUMER_KEY=${{ secrets.WOOCOMMERCE_CONSUMER_KEY }}" >> .env
        echo "WOOCOMMERCE_CONSUMER_SECRET=${{ secrets.WOOCOMMERCE_CONSUMER_SECRET }}" >> .env
